
local M = {}

-- Fails the chunk regex near the end:
M[1] = [[room.writtenmap Exits northwest and southeast of one southwest, the limit of your vision is one southwest from here, exits southwest and northeast of one southeast, a sneaky pickpocket and a fair wenche are one southeast, exits southwest and northeast of one northwest, a small boy and a brown rat are one northwest, the limit of your vision is one northwest from here, exits southeast and northwest of one northeast, a drowsy girl is one northeast, exits south and north of one west, a worn cat and a deliberate old woman are one west, exits south and north of one east, a twisty man is one east, exits northwest, northeast, west and east of one south, Zevgatis is one south, exits southwest, southeast, west and east of one north, a colourful middle-aged woman is one north, exits southeast, northeast, east and south of two southeast, an old cobbler is two southeast, the limit of your vision is two southeast from here, exits southeast, northwest, northeast, east and south of one southeast and one east, a contumelious slave and an idle labourer are one southeast and one east, the limit of your vision is one southeast and one east from here, exits northwest, northeast, east, south and southeast of one southeast and one south, the limit of your vision is one southeast and one south from here, exits southeast and east of two northeast, an agreeable philosopher and a small red orangutan are two northeast, the limit of your vision is two northeast from here, exits southwest, southeast, northeast, east and north of one northeast and one east, a scowling dark-skinned man is one northeast and one east, the limit of your vision is one northeast and one east from here, exits southwest, southeast and east of one northeast and one north, a wiry jeweller and a red-bearded dwarf are one northeast and one north, the limit of your vision is one northeast and one north from here, exits northeast and southeast of two west, exits southwest, southeast, northwest, northeast, east, south and north of two east, Ulive is two east, the limit of your vision is two east from here, exits northeast, southwest, northwest and east of two south, an enticing lady, an officious official and a parsimonious priestess are two south, the limit of your vision is two south from here, exits east, southeast and southwest of two north, a temperamental black goat is two north, the limit of your vision is two north from here, an exit north of two west and one north, a sanguinary hoplite, a sanguine hoplite, a stalwart hoplite and a handsome hoplite are two west and one north, an exit south of two west, one north, one northeast and one west, a worn cat and a torbie and white cat are two west, one north, one northeast and one west and the limit of your vision is two west, one north, one northeast and one west from here.\n" ]]

M[2] = [[Exits southeast and northwest of one southwest, a buzzing shopkeeper is one southwest, a door east of one southeast, exits southwest and northeast of one southeast, a supercilious jeweller is one southeast, the limit of your vision is one southeast, exits southwest and northeast of one northwest, a short flamboyant man is one northwest, exits southeast and northwest of one northeast, an adorable girl and a wispy-haired old woman are one northeast, the limit of your vision is one northeast, exits south and north of one west, a golden-muscled young man is one west, exits south and north of one east, a cheerful slave and an earnest little girl are one east, exits northwest, northeast, west and east of one south, an excited old man is one south, exits southwest, southeast, west and east of one north, a frail old lady is one north, exits southeast and south of two southwest, a rascally boy, a lazy black and white goat and Ulive are two southwest, the limit of your vision is two southwest, exits northeast and south of one southwest and one west, an enchanting lady and a scowling dark-skinned man are one southwest and one west, the limit of your vision is one southwest and one west, exits southwest, southeast, northwest, northeast, west and south of one southwest and one south, a putrescent beggar and a grinning young man are one southwest and one south, the limit of your vision is one southwest and one south, a morose philosopher is two northwest, the limit of your vision is two northwest, exits southeast and north of one northwest and one west, a dark uptight woman is one northwest and one west, the limit of your vision is one northwest and one west, exits southwest, southeast and west of one northwest and one north, a youthful silversmith is one northwest and one north, the limit of your vision is one northwest and one north, exits southeast, northeast, south and north of two west, a small red orangutan is two west, the limit of your vision is two west, exits southwest, northwest and east of two east, a staunch hoplite is two east, a door east of two south, exits southwest, west, northwest, south and northeast of two south, a pedantic slave is two south, the limit of your vision is two south, exits southwest, southeast and west of two north, a tired artisan, a grizzled man, an adorable girl, a wiry jeweller and a corrupt bureaucrat are two north, the limit of your vision is two north, an exit southeast of two east and one north, a sleek seagull is two east and one north, an exit southeast of two east, one north and one northwest, a suave sailor and a glossy seagull are two east, one north and one northwest, the limit of your vision is two east, one north and one northwest.]]

M[3] = [[room.writtenmap "Exits north and south of one east, an unwashed child is one east, a door north of one west, a peasant is one west, a door west of one south, a muscular brawler is one south, exits south, north and east of two east, the limit of your vision is two east from here, a tough character, a shady character and a muscular character are one west and one northwest, the limit of your vision is one west and one northwest from here, exits west and south of two south, a frail royal judge and a three-legged hound are two south, the limit of your vision is two south from here, a door west of two north and the limit of your vision is two north from here.\n"]]

M[4] = [[room.writtenmap "A door north of one west, an unwashed child is one north, an exit east of two east, the limit of your vision is two east from here, the limit of your vision is two west from here, an exit west of two north, a flowery florist is two north and the limit of your vision is two north from here.\n"]]

M[5] = [[room.writtenmap "Exits north and south of one east, a bumbling brown beetle is one east, a door north of one west, a fat bum is one west, a door west of one south, an unwashed child is one south, exits south, north and east of two east, the limit of your vision is two east from here, a tough character, a shady character and a muscular character are one west and one northwest, the limit of your vision is one west and one northwest from here, exits west and south of two south, a muscular brawler and a long-legged dog are two south, the limit of your vision is two south from here, a door west of two north and the limit of your vision is two north from here.\n"]]

M[6] = [[A rakish mongrel is one northwest, Khaybat is one south, a soft red vixen and a sly tinker are two northeast, the limit of your vision is two northeast from here, a burly warehouse worker, a three-legged cur and a drunk are two northwest, the limit of your vision is two northwest from here, a flustered washerwoman, a ragged black crow, a hard-working executioner and a drunk are two south, a nervous warehouse worker is three south, a merchant is five south and the limit of your vision is five south from here.]]

M[7] = [[room.writtenmap "A door west of here, a burly warehouse worker and a three-legged cur are one northwest, a dusty red dog fox and \u001b[4zMXP<C #eeeeeeMXP>Khaybat\u001b[3z are one south, exits west and east of two northeast, a sly tinker is two northeast, the limit of your vision is two northeast from here, a ragged black crow, a rakish mongrel and a drunk are two northwest, the limit of your vision is two northwest from here, exits east, west and south of two south, a nervous warehouse worker, a hard-working executioner and a drunk are two south and the limit of your vision is two south from here.\n"]]

M[8] = [[room.writtenmap "A door west of one southwest, exits northwest and south of one southwest, the limit of your vision is one southwest from here, exits west and east of one northeast and the limit of your vision is one northeast from here.\n"]]

M[9] = [["Exits northeast and south of one southeast, a rascally boy, an adorable slave and Zevgatis are one southeast, exits southeast and north of one northeast, a scornful slave and a colourful middle-aged woman are one northeast, a hardy athlete is one west, exits south and north of one east, a holy priest and a young girl are one east, exits northeast, east and northwest of one south, a proficient pickpocket and a petite lady are one south, exits east, southeast and southwest of one north, exits northeast, east, south and southeast of two southeast, an excited man is two southeast, the limit of your vision is two southeast from here, exits southeast, northwest, northeast, east and south of one southeast and one east, a brown rat and a fair wenche are one southeast and one east, the limit of your vision is one southeast and one east from here, exits southeast and east of two northeast, a wiry jeweller and a red-bearded dwarf are two northeast, the limit of your vision is two northeast from here, exits southwest, southeast, northeast, east and north of one northeast and one east, a drowsy girl is one northeast and one east, the limit of your vision is one northeast and one east from here, the limit of your vision is two west from here, exits northeast and south of one west and one northwest, a sneaky pickpocket is one west and one northwest, the limit of your vision is one west and one northwest from here, exits southwest, west, north and northeast of one west and one north, a black smoke kitten (hiding), a grubby woman and a bitter hoplite are one west and one north, the limit of your vision is one west and one north from here, an exit north of one west and one southwest, the limit of your vision is one west and one southwest from here, exits southwest, southeast, northwest, northeast, east, south and north of two east, a villainous beggar and a twisty man are two east, the limit of your vision is two east from here, exits northeast, north, southwest and east of one south and one southeast, the limit of your vision is one south and one southeast from here, exits east, southeast and south of one north and one northeast, a wiry trader and a self-confident athlete are one north and one northeast and the limit of your vision is one north and one northeast from here.\n"]]

M[10] = [["Exits northwest and south of one southwest, an experienced hoplite and a beautiful lady are one southwest, an exit northwest of one northeast, a patronising philosopher, a corrupt official, a cowardly athlete and a smelly beggar are one northeast, exits southwest and northeast of one northwest, the limit of your vision is one northwest from here, exits north and south of one west, an ancient cat and a noisy black goat are one west, exits west, east and southwest of one north, exits south and east of two southwest, the limit of your vision is two southwest from here, exits southeast, south and northeast of one southwest and one west, a stout hoplite is one southwest and one west, the limit of your vision is one southwest and one west from here, an exit east of two northeast, the limit of your vision is two northeast from here, exits east and southwest of one northeast and one north, the limit of your vision is one northeast and one north from here, exits southeast, northeast and south of two west, a giant tortoise and an adorable slave are two west, the limit of your vision is two west from here, exits southeast, southwest and east of two north and the limit of your vision is two north from here.\n"]]
-- NE is says there is: cowardly athlete, smelly beggar
-- when there really was: A patronising philosopher, a corrupt official, a cowardly athlete and a smelly beggar

M[11] = [["A giant tortoise, a dashing hawker and a cream donkey are one east, an exit south of one west, an eccentric philosopher and an unrefined philosopher are one west, exits south and east of two east, the limit of your vision is two east from here, a lined sailor and a brown seagull are one west and one northwest and the limit of your vision is one west and one northwest from here.\n"]]
-- E thinks there is only dashing hawker, cream donkey....
-- really there was A giant tortoise, a dashing hawker and a cream donkey

M[12] = [["A door southwest of here, an exit west of one northwest, a deep green tortoise, a harassed artisan and a speckled seagull are one northwest, exits south and east of one east and one southeast, a sneaky pickpocket is one east and one southeast, the limit of your vision is one east and one southeast from here, an exit south of two northwest, a grubby woman is two northwest and the limit of your vision is two northwest from here.\n"]]
-- It thinks to NW harassed artisan, speckled seagull...
-- really is A deep green tortoise is resting on the ground and a harassed artisan and a speckled seagull

-- Same room as above, plus salty sailor
M[13] = [["A door southwest of here, an exit west of one northwest, a grubby woman, a salty sailor, a deep green tortoise, a harassed artisan and a speckled seagull are one northwest, exits south and east of one east and one southeast, the limit of your vision is one east and one southeast from here, an exit south of two northwest and the limit of your vision is two northwest from here.\n"]]
-- still only thinks NW harassed artisan, speckled seagull

-- Same room again but now
M[14] = [["A door southwest of here, an exit west of one northwest, a grubby woman, a deep green tortoise and a speckled seagull are one northwest, exits south and east of one east and one southeast, the limit of your vision is one east and one southeast from here, an exit south of two northwest, a salty sailor and an emaciated boy are two northwest and the limit of your vision is two northwest from here.\n"]]
-- It thinks NW A deep green tortoise is resting on the ground and an emaciated boy, a grubby woman and a speckled seagull
-- which is correct

M[15] = [["An exit west of here, an exit northwest of one north, a door west of two south, an exit south of two south, a quiet fisherman, a broad-shouldered athlete, a greasy seagull and a sleek seagull are two south, the limit of your vision is two south from here, exits south and northeast of one north and one southwest, the limit of your vision is one north and one southwest from here and the limit of your vision is one north and one northeast from here.\n"]]
-- 2 S it thinks broad-shouldered athlete, greasy seagull, sleek seagull...
-- really is also a quiet fisherman

M[16] = [["Three priests and a worried looking warehouse worker are one north, an exit southwest of two south, the limit of your vision is two south from here, an exit west of one north and one northwest and the limit of your vision is one north and one northwest from here.\n"]]

-- Player hex color test.
M[17] = [["An exit north of here, exits north and south of one east, an exit south of two south, a sad man is two south, the limit of your vision is two south from here, an exit north of two west, the limit of your vision is two west from here, exits south and east of two east, \u001b[4zMXP<C #d7d7d7MXP>Antiquated Ordeith Fallstar\u001b[3z and \u001b[4zMXP<C #d7d7d7MXP>Aalia\u001b[3z are two east and the limit of your vision is two east from here.\n"]]

-- Player named color test.
M[18] = [["An exit south of here, exits south and north of one east, a tall skipper, \u001b[4zMXP<WhiteMXP>PtHemNetjer pteh Pterrible\u001b[3z, an accountant, a scruffy crow and Gnarmine the gnoll are one east, exits north and south of one west, an exit east of two east, \u001b[4zMXP<WhiteMXP>the net dead statue of Ptarptuffe pteh Pterrible\u001b[3z is two east, the limit of your vision is two east from here, exits north and south of two west and the limit of your vision is two west from here.\n"]]

-- Just a bunch of consecutive exits.
M[19] = [["Exits northwest and south of one southwest, an exit northwest of one northeast, exits southwest and northeast of one northwest, exits north and south of one west, exits west, east and southwest of one north, exits south and east of two southwest, exits southeast, south and northeast of one southwest and one west, a stout hoplite is one southwest and one west, the limit of your vision is one southwest and one west from here, an exit east of two northeast, exits east and southwest of one northeast and one north, exits southeast, northeast and south of two west, a giant tortoise and an adorable slave are two west, exits southeast, southwest and east of two north and the limit of your vision is two north from here.\n"]]

M[20] = [["A door west of here, exits east and west of one south, a door west of two south, \u001b[4zMXP<C #af00d7MXP>Westley\u001b[3z and \u001b[4zMXP<C #af00d7MXP>Eli\u001b[3z are two south and the limit of your vision is two south from here.\n"]]

return M
